version: 2.1

executors:
  pulumi:
    docker:
      - image: circleci/node:14

jobs:
  make:
    resource_class: xlarge
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: "make install"
      - run:
          command: "make test"
  upload-coverage:
    environment:
      - CC_TEST_REPORTER_ID: YOUR_REPO_CC_TEST_REPORTER_ID
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2
  build-master:
    jobs:
      - make:
        name: make
        env: prod
